### DISCUSSION TITLE
Restore getting wrong backup directory

### DISCUSSION THREAD

**Discussion by tamimology** [nfrastack/db-backup#516] [Legacy Q&A]
### Summary

The backup is going just fine with no issues. I have around 14 DB to be backed up in a single deployment in different folders, all go as defined in my compose

### Steps to reproduce

Opened the container's console and executed 'restore' and got a list of 310 items from a different folder, none of them are what I am after

### What is the expected *correct* behavior?

I should see my 14 DBs in the list to choose from, however, I had to choose the Custom option # 311

### Relevant logs and/or screenshots

![Image](https://github.com/user-attachments/assets/48f48c7b-337d-415e-b6b7-17ea69df0650)

### Environment

`.env' file contains the following variable

BACKUPS=/home/tam/backups

- Image version / tag:  latest
- Host OS: Ubuntu Server 22.04.2 LTS

<details>
<summary>

```
  databases-backup:
    container_name: databases-backup
    restart: $RESTART_POLICY
    hostname: databases-backup
    volumes:
      - $BACKUPS:/backup
      #- ./post-script.sh:/assets/custom-scripts/post-script.sh
    environment:
      - TIMEZONE=$TZ
      - USER_DBBACKUP=$PUID
      - GROUP_DBBACKUP=$PGID
      - CONTAINER_ENABLE_MONITORING=FALSE
      - LOG_PATH=/logs/logs
      - ENABLE_NOTIFICATIONS=true # only on job failure
      - NOTIFICATION_TYPE=email
      - MAIL_FROM=$GM_USER
      - MAIL_TO=$PUSHOVER_EMAIL_DATABASES_BACKUP
      - SMTP_HOST=$GM_HOST
      - SMTP_PORT=$GM_PORT

    # authelia-redis-backup
      - DB01_TYPE=redis
      - DB01_HOST=authelia-redis
      - DB01_PORT=6379
      - DB01_BACKUP_LOCATION=FILESYSTEM
      - DB01_FILESYSTEM_PATH=/backup/redis/authelia
      - DB01_BACKUP_INTERVAL=1440 #once per day
      - DB01_BACKUP_BEGIN="2355" # @23:55 midnight
      - DB01_CLEANUP_TIME=8640 # keep for 6 days
      - DB01_CHECKSUM=SHA1
      - DB01_COMPRESSION=ZSTD
      - DB01_COMPRESSION_LEVEL=10
      - DB01_SPLIT_DB=false
      - DB01_MYSQL_SINGLE_TRANSACTION=true

    # homeassistant-mariadb-backup
      - DB02_TYPE=mariadb
      - DB02_HOST=homeassistant-mariadb
      - DB02_PORT=3306
      - DB02_NAME=homeassistant
      - DB02_USER=homeassistant
      - DB02_PASS=$DB_PASSWORD
      - DB02_BACKUP_LOCATION=FILESYSTEM
      - DB02_FILESYSTEM_PATH=/backup/mariadb/homeassistant
      - DB02_BACKUP_INTERVAL=1440 #once per day
      - DB02_BACKUP_BEGIN="0000" # @00:00 midnight
      - DB02_CLEANUP_TIME=8640 # keep for 6 days
      - DB02_CHECKSUM=SHA1
      - DB02_COMPRESSION=ZSTD
      - DB02_COMPRESSION_LEVEL=10
      - DB02_SPLIT_DB=false
      - DB02_MYSQL_SINGLE_TRANSACTION=true

    # # mariadb-sys-backup
    #   - DB03_TYPE=mariadb
    #   - DB03_HOST=mariadb
    #   - DB03_PORT=3306
    #   - DB03_NAME=all
    #   - DB03_NAME_EXCLUDE=homeassistant,pastefy,projectsend,traccar,tasmobackupdb
    #   - DB03_USER=root
    #   - DB03_PASS=$DB_PASSWORD
    #   - DB03_BACKUP_LOCATION=FILESYSTEM
    #   - DB03_FILESYSTEM_PATH=/backup/mariadb/sys
    #   - DB03_BACKUP_INTERVAL=1440 #once per day
    #   - DB03_BACKUP_BEGIN="0005" # @00:05 midnight
    #   - DB03_CLEANUP_TIME=8640 # keep for 6 days
    #   - DB03_CHECKSUM=SHA1
    #   - DB03_COMPRESSION=ZSTD
    #   - DB03_COMPRESSION_LEVEL=10
    #   - DB03_SPLIT_DB=false
    #   - DB03_MYSQL_SINGLE_TRANSACTION=true

    # pastefy-mariadb-backup
      - DB04_TYPE=mariadb
      - DB04_HOST=pastefy-mariadb
      - DB04_PORT=3306
      - DB04_NAME=pastefy
      - DB04_USER=pastefy
      - DB04_PASS=$DB_PASSWORD
      - DB04_BACKUP_LOCATION=FILESYSTEM
      - DB04_FILESYSTEM_PATH=/backup/mariadb/pastefy
      - DB04_BACKUP_INTERVAL=1440 #once per day
      - DB04_BACKUP_BEGIN="0010" # @00:10 midnight
      - DB04_CLEANUP_TIME=8640 # keep for 6 days
      - DB04_CHECKSUM=SHA1
      - DB04_COMPRESSION=ZSTD
      - DB04_COMPRESSION_LEVEL=10
      - DB04_SPLIT_DB=false
      - DB04_MYSQL_SINGLE_TRANSACTION=true

    # projectsend-mariadb-backup
      - DB05_TYPE=mariadb
      - DB05_HOST=projectsend-mariadb
      - DB05_PORT=3306
      - DB05_NAME=projectsend
      - DB05_USER=projectsend
      - DB05_PASS=$DB_PASSWORD
      - DB05_BACKUP_LOCATION=FILESYSTEM
      - DB05_FILESYSTEM_PATH=/backup/mariadb/projectsend
      - DB05_BACKUP_INTERVAL=1440 #once per day
      - DB05_BACKUP_BEGIN="0015" # @00:15 midnight
      - DB05_CLEANUP_TIME=8640 # keep for 6 days
      - DB05_CHECKSUM=SHA1
      - DB05_COMPRESSION=ZSTD
      - DB05_COMPRESSION_LEVEL=10
      - DB05_SPLIT_DB=false
      - DB05_MYSQL_SINGLE_TRANSACTION=true

    # traccar-mariadb-backup
      - DB06_TYPE=mariadb
      - DB06_HOST=traccar-mariadb
      # - DB06_PORT=3307
      - DB06_NAME=traccar
      - DB06_USER=traccar
      - DB06_PASS=$DB_PASSWORD
      - DB06_BACKUP_LOCATION=FILESYSTEM
      - DB06_FILESYSTEM_PATH=/backup/mariadb/traccar
      - DB06_BACKUP_INTERVAL=1440 #once per day
      - DB06_BACKUP_BEGIN="0020" # @00:20 midnight
      - DB06_CLEANUP_TIME=8640 # keep for 6 days
      - DB06_CHECKSUM=SHA1
      - DB06_COMPRESSION=ZSTD
      - DB06_COMPRESSION_LEVEL=10
      - DB06_SPLIT_DB=false
      - DB06_MYSQL_SINGLE_TRANSACTION=true

    # # endurain-postgres-backup
      - DB07_TYPE=pgsql
      - DB07_HOST=endurain-postgres
      - DB07_USER=endurain
      - DB07_AUTH=endurain
      - DB07_PASS=$DB_PASSWORD
      - DB07_NAME=endurain
      - DB07_BACKUP_LOCATION=FILESYSTEM
      - DB07_FILESYSTEM_PATH=/backup/postgres/endurain
      - DB07_SPLIT_DB=false
      - DB07_BACKUP_INTERVAL=1440 #once per day
      - DB07_BACKUP_BEGIN="0025" # @00:25 midnight
      - DB07_CLEANUP_TIME=8640 # keep for 6 days
      - DB07_COMPRESSION=ZSTD
      - DB07_COMPRESSION_LEVEL=10
      - DB07_CHECKSUM=SHA1
      - DB07_MYSQL_SINGLE_TRANSACTION=true

    # # invidious-postgres-backup
      - DB08_TYPE=pgsql
      - DB08_HOST=invidious-postgres
      - DB08_USER=invidious
      - DB08_AUTH=invidious
      - DB08_PASS=$DB_PASSWORD
      - DB08_NAME=invidious
      - DB08_BACKUP_LOCATION=FILESYSTEM
      - DB08_FILESYSTEM_PATH=/backup/postgres/invidious
      - DB08_SPLIT_DB=false
      - DB08_BACKUP_INTERVAL=1440 #once per day
      - DB08_BACKUP_BEGIN="0030" # @00:30 midnight
      - DB08_CLEANUP_TIME=8640 # keep for 6 days
      - DB08_COMPRESSION=ZSTD
      - DB08_COMPRESSION_LEVEL=10
      - DB08_CHECKSUM=SHA1
      - DB08_MYSQL_SINGLE_TRANSACTION=true

    # # jellystat-postgres-backup
      - DB09_TYPE=pgsql
      - DB09_HOST=jellystat-postgres
      - DB09_USER=jellystat
      - DB09_AUTH=jellystat
      - DB09_PASS=$DB_PASSWORD
      - DB09_NAME=jfstat
      - DB09_BACKUP_LOCATION=FILESYSTEM
      - DB09_FILESYSTEM_PATH=/backup/postgres/jellystat
      - DB09_SPLIT_DB=false
      - DB09_BACKUP_INTERVAL=1440 #once per day
      - DB09_BACKUP_BEGIN="0035" # @00:35 midnight
      - DB09_CLEANUP_TIME=8640 # keep for 6 days
      - DB09_COMPRESSION=ZSTD
      - DB09_COMPRESSION_LEVEL=10
      - DB09_CHECKSUM=SHA1
      - DB09_MYSQL_SINGLE_TRANSACTION=true

    # # focalboard-postgres-backup
      - DB10_TYPE=pgsql
      - DB10_HOST=focalboard-postgres
      - DB10_USER=focalboard
      - DB10_AUTH=focalboard
      - DB10_PASS=$DB_PASSWORD
      - DB10_NAME=focalboard
      - DB10_BACKUP_LOCATION=FILESYSTEM
      - DB10_FILESYSTEM_PATH=/backup/postgres/focalboard
      - DB10_SPLIT_DB=false
      - DB10_BACKUP_INTERVAL=1440 #once per day
      - DB10_BACKUP_BEGIN="0040" # @00:40 midnight
      - DB10_CLEANUP_TIME=8640 # keep for 6 days
      - DB10_COMPRESSION=ZSTD
      - DB10_COMPRESSION_LEVEL=10
      - DB10_CHECKSUM=SHA1
      - DB10_MYSQL_SINGLE_TRANSACTION=true

    # # paperless-ngx-postgres-backup
      - DB11_TYPE=pgsql
      - DB11_HOST=paperless-ngx-postgres
      - DB11_USER=paperless
      - DB11_AUTH=paperless
      - DB11_PASS=$DB_PASSWORD
      - DB11_NAME=paperless
      - DB11_BACKUP_LOCATION=FILESYSTEM
      - DB11_FILESYSTEM_PATH=/backup/postgres/paperless
      - DB11_SPLIT_DB=false
      - DB11_BACKUP_INTERVAL=1440 #once per day
      - DB11_BACKUP_BEGIN="0045" # @00:45 midnight
      - DB11_CLEANUP_TIME=8640 # keep for 6 days
      - DB11_COMPRESSION=ZSTD
      - DB11_COMPRESSION_LEVEL=10
      - DB11_CHECKSUM=SHA1
      - DB11_MYSQL_SINGLE_TRANSACTION=true

    # paperless-ngx-redis-backup
      - DB12_TYPE=redis
      - DB12_HOST=paperless-ngx-redis
      - DB12_USER=paperless
      - DB12_AUTH=paperless
      - DB12_PASS=$DB_PASSWORD
      - DB12_PORT=6379
      - DB12_BACKUP_LOCATION=FILESYSTEM
      - DB12_FILESYSTEM_PATH=/backup/redis/paperless
      - DB12_BACKUP_INTERVAL=1440 #once per day
      - DB12_BACKUP_BEGIN="0050" # @00:50 midnight
      - DB12_CLEANUP_TIME=8640 # keep for 6 days
      - DB12_CHECKSUM=SHA1
      - DB12_COMPRESSION=ZSTD
      - DB12_COMPRESSION_LEVEL=10
      - DB12_SPLIT_DB=false
      - DB12_MYSQL_SINGLE_TRANSACTION=true

    # immich-redis-backup
      - DB13_TYPE=redis
      - DB13_HOST=immich-redis
      - DB13_PORT=6379
      - DB13_BACKUP_LOCATION=FILESYSTEM
      - DB13_FILESYSTEM_PATH=/backup/redis/immich
      - DB13_BACKUP_INTERVAL=1440 #once per day
      - DB13_BACKUP_BEGIN="0055" # @00:55 midnight
      - DB13_CLEANUP_TIME=8640 # keep for 6 days
      - DB13_CHECKSUM=SHA1
      - DB13_COMPRESSION=ZSTD
      - DB13_COMPRESSION_LEVEL=10
      - DB13_SPLIT_DB=false
      - DB13_MYSQL_SINGLE_TRANSACTION=true

    # # immich-postgres-backup
      - DB14_TYPE=pgsql
      - DB14_HOST=immich-postgres
      - DB14_USER=immichuser
      - DB14_AUTH=immich
      - DB14_PASS=$DB_PASSWORD
      - DB14_NAME=immich
      - DB14_BACKUP_LOCATION=FILESYSTEM
      - DB14_FILESYSTEM_PATH=/backup/postgres/immich
      - DB14_SPLIT_DB=false
      - DB14_BACKUP_INTERVAL=1440 #once per day
      - DB14_BACKUP_BEGIN="0100" # @01:00 midnight
      - DB14_CLEANUP_TIME=8640 # keep for 6 days
      - DB14_COMPRESSION=ZSTD
      - DB14_COMPRESSION_LEVEL=10
      - DB14_CHECKSUM=SHA1
      - DB14_MYSQL_SINGLE_TRANSACTION=true

    # # # maybe-postgres-backup
    #   - DB15_TYPE=pgsql
    #   - DB15_HOST=maybe-postgres
    #   - DB15_USER=maybe
    #   - DB15_AUTH=maybedb
    #   - DB15_PASS=$DB_PASSWORD
    #   - DB15_NAME=maybedb
    #   - DB15_BACKUP_LOCATION=FILESYSTEM
    #   - DB15_FILESYSTEM_PATH=/backup/postgres/maybe
    #   - DB15_SPLIT_DB=false
    #   - DB15_BACKUP_INTERVAL=1440 #once per day
    #   - DB15_BACKUP_BEGIN="0105" # @01:05 midnight
    #   - DB15_CLEANUP_TIME=8640 # keep for 6 days
    #   - DB15_COMPRESSION=ZSTD
    #   - DB15_COMPRESSION_LEVEL=10
    #   - DB15_CHECKSUM=SHA1
    #   - DB15_MYSQL_SINGLE_TRANSACTION=true
    links:
      - authelia-redis
      - immich-redis
      - paperless-ngx-redis
      - homeassistant-mariadb
      - pastefy-mariadb
      - projectsend-mariadb
      - traccar-mariadb
      - endurain-postgres
      - focalboard-postgres
      - immich-postgres
      - invidious-postgres
      - jellystat-postgres
      # - maybe-postgres
      - paperless-ngx-postgres
    labels: 
      monocker.enable: $MONOCKER_ENABLE
    image: 'tiredofit/db-backup:latest'
```
</summary>
</details>

    
### Possible fixes
I never had this issue in the past and I have not changed any thing in my configuration, only adding new DBs to the container as needed.
