### DISCUSSION TITLE
db-backup version 4.1.10 not working

### DISCUSSION THREAD

**Discussion by ch3lmi** [nfrastack/db-backup#520] [Legacy Q&A]
### Summary

Since switching to 4.1.10 the following error message is displayed and no backup is started:
```
sudo: /usr/bin/mariadb-: command not found
```

Previously working 4.1.9 displayed
```
/usr/bin/mysqldump: Deprecated program name. It will be removed in a future release, use '/usr/bin/mariadb-dump' instead
```

### Steps to reproduce

run backup-now on 4.1.10 

### What is the expected *correct* behavior?

backup is achieved successfully

### Relevant logs and/or screenshots

```
2024-12-13.08:55:06 [INFO] ** [db-backup01] Starting Manual Backup for db-backup01
sudo: /usr/bin/mariadb-: command not found
```

### Environment

- Image version / tag:  4.1.10
- Host OS: coreOS 41

```yaml
services:
  db-backup:
    container_name: db-backup
    image: tiredofit/db-backup
    restart: unless-stopped
    volumes:
      - dbbackup:/backup
      - post:/assets/scripts/post
    environment:
      - TZ=Europe/Zurich
      - ZABBIX_HOSTNAME=db-backup
      - DB01_HOST=xxxxx
      - DB01_TYPE=mariadb
      - DB01_NAME=ALL
      - DB01_USER=xxxxxx
      - DB01_PASS=xxxxxx
      - DEFAULT_BACKUP_BEGIN=0000
      - DEFAULT_BACKUP_INTERVAL=1440      
      - DEFAULT_CLEANUP_TIME=8640
      - DEFAULT_COMPRESSION=BZ
      - DEFAULT_CHECKSUM=MD5
      - DB01_POST_SCRIPT=/assets/scripts/post/post.sh 
      - CONTAINER_ENABLE_MONITORING=FALSE

volumes:
  post:
  dbbackup: 
```
