### DISCUSSION TITLE
DB01_BACKUP_BLACKOUT parameters ain't working as expected

### DISCUSSION THREAD

**Discussion by rltas** [nfrastack/db-backup#549] [Legacy Q&A]
### Summary

With a blackout period of 1800 to 0800, backups are still running hourly with the default backup begin time of 2am.

### Steps to reproduce

compose.yaml:
```
...
services:
  db-backup:
    image: tiredofit/db-backup:4.1.4
    environment:
      DEFAULT_BACKUP_BEGIN: "0200"
      DB01_BACKUP_INTERVAL: ${DB_BACKUP_INTERVAL:-1440}
      DB01_BACKUP_BLACKOUT_BEGIN: ${DB_BACKUP_BLACKOUT_BEGIN}
      DB01_BACKUP_BLACKOUT_END: ${DB_BACKUP_BLACKOUT_END}
...
```

.env:
```
DB_BACKUP_INTERVAL=60
DB_BACKUP_BLACKOUT_BEGIN=1800
DB_BACKUP_BLACKOUT_END=0800
```

Resulting in this actual container environment:

```
DB01_BACKUP_BLACKOUT_BEGIN=1800
DB01_BACKUP_BLACKOUT_END=0800
DB01_BACKUP_INTERVAL=60
DEFAULT_BACKUP_BEGIN=0200
```

### What is the expected *correct* behavior?

Backups aren't running between 1800 and 0800.

### Possible fixes

https://github.com/tiredofit/docker-db-backup/blob/4fc54e2232f02a1062f57ac7c945248dea6a7ae6/install/assets/dbbackup/template-dbbackup/run#L73
https://github.com/tiredofit/docker-db-backup/blob/4fc54e2232f02a1062f57ac7c945248dea6a7ae6/install/assets/functions/10-db-backup#L204
Shouldn't these match?
